const root = document.querySelector('#app');
const initial = () => ({step:0, start:'2027-05-10',end:'2027-05-16',people:2,budget:1800,pace:'Balanced',interests:['Food','Culture'],changed:false,ready:false});
let state=initial();
let history=[];
const titles=['A world of possibility.','Your next chapter: Italy.','Make it your kind of trip.','Leave room for what you love.','Your Italy itinerary.','A closer look.','Know where your money goes.','A few things before you go.','Today, at your pace.','A change of plan.','You’re back on track.','Keep the good parts.'];
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const euros=n=>new Intl.NumberFormat('en',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const card=(title,detail)=>`<div class="app-card"><strong>${title}</strong><span>${detail}</span></div>`;
const action=(label,next,secondary=false)=>`<button type="button" data-next="${next}" class="${secondary?'secondary':''}">${label}</button>`;
const days=()=>Math.max(1,Math.round((new Date(state.end+'T12:00:00')-new Date(state.start+'T12:00:00'))/86400000)+1);
function render(){
 let body='',actions='';
 const nights=Math.max(0,days()-1);
 const total=(nights*55+days()*55)*state.people+(state.changed?state.people*15:0);
 switch(state.step){
 case 0:body='<img class="app-art" src="assets/travel-hero.png" alt="Playful travel illustration with a plane, palm and luggage"><p>Save the places you love. Shape a realistic plan. Keep discovering along the way.</p>';actions=action('Explore & plan',1)+'<p class="small">Continue as a guest. No account needed.</p>';break;
 case 1:body='<img class="app-art destination-art" src="assets/italy.jpg" alt="Colorful coastal village in Italy">'+card('Italy','Slow mornings. Ancient streets. A table worth finding.')+card('A flexible journey','Rome → Florence · one country, room to explore')+'<p class="small">Check current destination information before booking.</p>';actions=action('Plan Italy',2);break;
 case 2:body=`<label>Start date<input id="start" type="date" value="${state.start}"></label><label>End date<input id="end" type="date" value="${state.end}"></label><label>Travelers<select id="people">${[1,2,3,4].map(n=>`<option ${n===state.people?'selected':''}>${n}</option>`).join('')}</select></label><label>Group budget · EUR<input id="budget" type="number" min="100" step="50" value="${state.budget}"></label><p class="small">This route supports trips of 3–14 days. Budget covers this group’s stay, activities, food and local transport. International flights are excluded.</p><p id="form-error" role="alert" class="error"></p>`;actions='<button type="button" id="save-details">Continue</button>';break;
 case 3:body=`<label>Your pace<select id="pace">${['Easygoing','Balanced','Full days'].map(p=>`<option ${p===state.pace?'selected':''}>${p}</option>`).join('')}</select></label><fieldset><legend>What would you make time for?</legend>${['Food','Culture','Nature','Shopping'].map(x=>`<label class="check"><input type="checkbox" name="interest" value="${x}" ${state.interests.includes(x)?'checked':''}>${x}</label>`).join('')}</fieldset>`+card('You’re in control','Your trip summary and cost estimate adapt to your choices. The route stays in Rome and Florence.');actions='<button type="button" id="build-plan">Build my plan</button>';break;
 case 4:body=`<p>${days()} days · ${state.people} traveler${state.people>1?'s':''} · ${escapeHTML(state.pace)}</p><p class="small">${state.start} → ${state.end} · ${state.interests.map(escapeHTML).join(' + ')||'Open to discovery'}</p>`+card('Day 1 · Arrive in Rome','Check in, settle in, then a short neighborhood walk.')+card('Day 2 · Rome, unhurried',state.changed?'Indoor gallery → long lunch → open afternoon':'Historic center → long lunch → garden walk')+card('Day 3 onward · Shape the rest','Florence is a suggested next stop. Confirm rail times and accommodation before committing.')+'<p class="small">Trip itinerary · activities are not booked.</p>';actions=action('Explore a day',5)+action('Review the budget',6,true);break;
 case 5:body=card('09:30 · Historic center','Allow 90 minutes. Opening times need checking.')+card('11:00 · A little breathing room','30-minute travel buffer before lunch.')+card('12:00 · Lunch near your next stop','Planning allowance: €25 per person.')+card('14:00 · Garden walk','Optional, weather dependent. Leave the evening open.');actions=action('Review trip budget',6)+action('Back to itinerary',4,true);break;
 case 6:body=card('Estimated group total',euros(total))+card('Stays',`${euros(nights*state.people*55)} · ${nights} nights, planning allowance`)+card('Food, local travel & activities',`${euros(days()*state.people*55)} · estimates, not quotes`)+(state.changed?card('Gallery replacement',`${euros(state.people*15)} · added to estimate`):'')+card(total>state.budget?'Above your target':'Within your target',`${euros(Math.abs(state.budget-total))} ${total>state.budget?'over':'remaining'} · target ${euros(state.budget)}`)+'<p class="small">Estimates exclude international flights and insurance. Confirm current provider prices before booking.</p>';actions=action('Prepare for the trip',7)+action('Edit dates or budget',2,true);break;
 case 7:body=card('Reservations · action needed','No hotel, rail or activity booking is confirmed in this planner.')+card('Documents · check requirements','Review entry requirements with official sources for your passport and destination.')+`<label class="check"><input type="checkbox" id="ready" ${state.ready?'checked':''}>I reviewed this preparation checklist</label>`+'<p class="small">Documents stay on the device; an offline pack includes download status and a last-updated time.</p>';actions=action('Preview travel day',8);break;
 case 8:body=card('Rome · Day 2','Travel-day view')+card('Next · Lunch in the center','Your next useful action, without the full planning interface.')+card('Weather change','Rain may affect the garden walk. Review an indoor alternative.')+'<p class="small">Simulated condition, not a live weather alert.</p>';actions=action('Review an alternative',9)+action('Open itinerary',4,true);break;
 case 9:body=card('Current plan','Garden walk · optional · no booking')+card('Indoor alternative','Indoor gallery · ticket estimate €15 per person')+card('What changes',`${euros(state.people*15)} additional group spend. Lunch stays in place. Allow a 20-minute travel buffer.`)+'<p class="small">Availability and opening times need checking. Applying this change only edits the itinerary.</p>';actions='<button type="button" id="apply-change">Use this alternative</button>'+action('Keep original plan',8,true);break;
 case 10:body='<div class="app-card success"><strong>Itinerary updated</strong><span>The indoor gallery replaces the garden walk. Your other stops stay in place.</span></div>'+card('You can undo this','No reservation was made or canceled.')+'<p class="small">The additional gallery estimate is included in your budget. Collaborator updates are outside this journey.</p>';actions=action('See updated itinerary',4)+'<button type="button" id="undo-change" class="secondary">Undo change</button>'+action('Preview trip recap',11,true);break;
 case 11:body=card('A trip worth keeping','Save the places you would return to and the decisions that worked.')+card('Reflect, then reuse','A future version can compare planned and recorded spend and export your itinerary.')+'<p class="small">You’ve reached the end of this journey. Try the visual city planner in the case study to build your own day.</p>';actions=action('Return to itinerary',4);break;
 }
 root.innerHTML=`${state.step?'<button type="button" class="back" id="back">← Back</button>':'<img src="logo.svg" width="40" height="40" alt="Veyra">'}<p class="eyebrow">Veyra / ${String(state.step+1).padStart(2,'0')}</p><h3 tabindex="-1">${titles[state.step]}</h3>${body}<div class="actions">${actions}</div>`;
}
root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const previous=state.step;if(b.dataset.next!==undefined)state.step=Number(b.dataset.next);else if(b.id==='back')state.step=history.length?history.pop():0;else if(b.id==='save-details'){const start=root.querySelector('#start').value,end=root.querySelector('#end').value,budget=Number(root.querySelector('#budget').value);if(!start||!end||!Number.isFinite(budget)||budget<100||new Date(end+'T12:00:00')-new Date(start+'T12:00:00')<2*86400000||new Date(end+'T12:00:00')-new Date(start+'T12:00:00')>13*86400000){root.querySelector('#form-error').textContent='For this route, choose a 3–14 day trip and a budget of at least €100.';return;}state.start=start;state.end=end;state.budget=budget;state.people=Number(root.querySelector('#people').value);state.step=3;}else if(b.id==='build-plan'){state.pace=root.querySelector('#pace').value;state.interests=[...root.querySelectorAll('[name=interest]:checked')].map(x=>x.value);state.step=4;}else if(b.id==='apply-change'){state.changed=true;state.step=10;}else if(b.id==='undo-change'){state.changed=false;state.step=4;}else return;if(b.id!=='back'&&state.step!==previous)history.push(previous);render();root.querySelector('h3').focus({preventScroll:true});});
root.addEventListener('change',e=>{if(e.target.id==='ready')state.ready=e.target.checked;});
document.querySelector('#reset-demo').addEventListener('click',()=>{state=initial();history=[];render();root.querySelector('h3').focus({preventScroll:true});});render();
